Fixed: sub domain regex w/ -
Also added resync-accounts from util.php

diff --git a/aronode b/aronode
--- a/aronode
+++ b/aronode
@@ -26,6 +26,7 @@ usage() {
     echo "  require    -- install aronode script requirements"
     echo "  reset      -- set Aronode environment config to testnet or mainnet; then rebuild blockchain"
     echo "  restart    -- restart all Arionum related services; php/nginx/mysql"
+    echo "  resync-accounts -- check ALL account balances table; time consuming."
     echo "  stop       -- stop public facing Arionum related services; php/nginx"
     echo "  status     -- check status of services"
     echo "  sync       -- runs sanity.php manually so you can monitor the sync; CTRL+C to kill"
@@ -186,6 +187,7 @@ if [[ -z "2" || (
     "$2" != "require" &&
     "$2" != "reset" &&
     "$2" != "restart" &&
+    "$2" != "resync-accounts" &&
     "$2" != "stop" &&
     "$2" != "status" &&
     "$2" != "sync" &&
@@ -948,7 +950,7 @@ nodeInstall() {
     checkRAM
     if [[ "$ARG_CONFIG_MODE" == "mainnet" && $RAMTOTAL -lt 1800 ]]; then
         echo ""
-        read -p "WARNING: Detected < 2GB RAM. Node may have issues syncing beyond block 10800. Continue? (yes|no): " USER_RAM_CONTINUE
+        read -pr "WARNING: Detected < 2GB RAM. Node may have issues syncing beyond block 10800. Continue? (yes|no): " USER_RAM_CONTINUE
         if ! [[ "$USER_RAM_CONTINUE" == "yes" ]]; then
             echo -e "$ERROR_CHAR You did not type 'yes'. Halting setup.\n"
             exitAsError
@@ -958,7 +960,7 @@ nodeInstall() {
     # Prompt user for domain name
     echo ""
     echo "$INFO_CHAR You can access the node via the main server IP address. A domain name is optional."
-    read -p "QUESTION: Enter a custom domain name (arionum.com): " DOMAIN
+    read -pr "QUESTION: Enter a custom domain name (arionum.com): " DOMAIN
     if [[ "$DOMAIN" == "" ]]; then
         DOMAIN="arionum.com"
     fi
@@ -966,7 +968,7 @@ nodeInstall() {
     DOMAIN=`echo "$DOMAIN" | awk '{print tolower($0)}'`
     # strip www. from beginning
     DOMAIN=`echo "$DOMAIN" | sed -e "s/^www\.//"`
-    REGEX='^[a-z]+[a-z0-9\-\.]{1,252}[a-z]{2,24}$';
+    REGEX="^[a-z][a-z0-9\.-]{1,252}[a-z\.]{2,24}$";
     if ! [[ "$DOMAIN" =~ $REGEX ]]; then
         echo "$ERROR_CHAR Invalid domain entered ..."
         exitAsError
@@ -1248,7 +1250,7 @@ nodeDropDb() {
 nodeRemove() {
 
     echo ""
-    read -p "WARNING: This will purge ALL Nginx|Php-fpm|Mysql AND Arionum content. Continue? (yes|no): " USER_REMOVE_CONTINUE
+    read -pr "WARNING: This will purge ALL Nginx|Php-fpm|Mysql AND Arionum content. Continue? (yes|no): " USER_REMOVE_CONTINUE
     if ! [[ "$USER_REMOVE_CONTINUE" == "yes" ]]; then
         echo -e "$ERROR_CHAR You did not type 'yes'. Halting setup.\n"
         exitAsError
@@ -1302,7 +1304,7 @@ nodeMainnetConfig() {
     checkRAM
     if [[ $RAMTOTAL -lt 1800 ]]; then
         echo ""
-        read -p "WARNING: Detected < 2GB RAM. Node may have issues syncing beyond block 10800. Continue? (yes|no): " USER_RAM_CONTINUE
+        read -pr "WARNING: Detected < 2GB RAM. Node may have issues syncing beyond block 10800. Continue? (yes|no): " USER_RAM_CONTINUE
         if ! [[ "$USER_RAM_CONTINUE" == "yes" ]]; then
             echo -e "$ERROR_CHAR You did not type 'yes'. Halting setup.\n"
             exitAsError
@@ -1446,11 +1448,11 @@ nodeChangeHostname() {
     echo "$INFO_CHAR Other peers will see this hostname in their peers list."
     echo "$INFO_CHAR You may enter a domain name but it must resolve to your server or risk failing to sync."
 
-    # TDOO: read -p "QUESTION: Do you want your node use a domain OR an IP4 address? (ip|domain): " USER_IPORDOMAIN
+    # TDOO: read -pr "QUESTION: Do you want your node use a domain OR an IP4 address? (ip|domain): " USER_IPORDOMAIN
     # TODO: check if user enter ip or domain as option
     # TODO: if entered 'ip' ask for it
     # TODO: if entered 'domain' ask for it
-    read -p "QUESTION: Enter new node hostname OR public IP4 address ($DETECT_IP4): " NEWHOSTNAME
+    read -pr "QUESTION: Enter new node hostname OR public IP4 address ($DETECT_IP4): " NEWHOSTNAME
     if [[ "$NEWHOSTNAME" == "" ]]; then
         NEWHOSTNAME="$DETECT_IP4"
     fi
@@ -1474,7 +1476,7 @@ nodeChangeHostname() {
     echo "$INFO_CHAR You entered: $NEWHOSTNAME"
     echo "$INFO_CHAR We detected: $DETECT_IP4"
     if ! [[ "$DETECT_IP4" == "$NEWHOSTNAME" ]]; then
-        read -p "QUESTION: hostname you entered and IP we detected do NOT match. Continue anyways? (yes|no) " USER_IP4_CONTINUE
+        read -pr "QUESTION: hostname you entered and IP we detected do NOT match. Continue anyways? (yes|no) " USER_IP4_CONTINUE
         if ! [[ "$USER_IP4_CONTINUE" == "yes" ]]; then
             echo -e "$ERROR_CHAR You did not type 'yes'. Halting setup.\n"
             exitAsError
@@ -1713,6 +1715,21 @@ case "$ARG_CALL" in
         nodeStart
         queueSanity
         nodeStatus
+        ;;
+    "resync-accounts")
+        startLogging
+        echo ""
+        read -pr "WARNING: Will check ALL account balances & may take a long time. Continue? (yes|no): " RESYNCACCNT_CONTINUE
+        if ! [[ "$RESYNCACCNT_CONTINUE" == "yes" ]]; then
+            echo -e "$ERROR_CHAR You did not type 'yes'. Halting.\n"
+            exitAsError
+        fi
+        # run resync-accounts
+        echo "$INFO_CHAR Resyncing accounts ... (PLEASE WAIT) ..."
+        PWD=`pwd`
+        cd $DOMAINROOT
+        php -f util.php resync-accounts
+        cd $PWD
         ;;
     "status")
         nodeStatus
